### ISSUE TITLE
Dropdown Select HTML, CSS, JS

### ISSUE THREAD

**Issue by davodey** [pearson-ux/web-components#139]
Lets create a similar style select menu using a listbox and form elements.

Use the markup kit to build out dropdowns with accessible markup and behavior, styled to UXF specification.

Markup kit:
https://github.com/pearson-ux/web-component-markup-kit

Framework specification
https://uxframework.pearson.com/c/dropdown

**Comment by annehong** [comment]
Hi and sorry, 

There is a minor request from Mike Krolak that we follow the dropdown styles from Gravity, specifically this link: https://ux.pearson.com/gravity/c/inputs#select-dropdown

The reason why they want the change done here is that they want to use the same class names and re-use the same components across all learning app applications. They're trying to iron out all the inconsistencies. :)

Thank you,
Anne

**Comment by davodey** [comment]
Closing - this has been implemented as a basic select in Gravity.
