### ISSUE TITLE
New Component Spike

### ISSUE THREAD

**Issue by davodey** [pearson-ux/web-components#143]
Let's look at other frameworks, bootstrap, foundation, material, other pearson projects, and make our library more robust by adding components we may need in the future.

If you see a component we need please create an issue for it and provide as much documentation as possible.  Links, images, etc... are all helpful.

**Comment by pauljadam** [comment]
I added one for Data Table & Sortable Data Table, https://github.com/pearson-ux/web-components/issues/183
