### ISSUE TITLE
How to use this modal in react js ?

### ISSUE THREAD

**Issue by itjayaprakash** [pearson-ux/web-components#164]
Hi Team,

How to use this modal in react js project

https://github.com/pearson-ux/web-components/tree/master/modal

what is steps to import and use this modal.

Thanks
J.Jayaprakash

**Comment by antelopeb** [comment]
Please see the README. The usage is the same in React.js and Angular.js, you call it like you would call any other HTML element in your JSX. If you need additional examples, please contact @davodey.
