### ISSUE TITLE
how to use webcomponent in react

### ISSUE THREAD

**Issue by PrasannaBrabourame** [pearson-ux/web-components#165]
Since pearson is using shadow dom approach how to import the shadow dom approach in React application.
since we are developing project on react its little bit difficult than the normal packages.

**Comment by davodey** [comment]
@dengeist did we address this?

**Comment by PrasannaBrabourame** [comment]
@dengeist any updates?

**Comment by davodey** [comment]
@PrasannaBrabourame our documentation now includes instructions on how to use WC in React.
