### ISSUE TITLE
[Bug] File Upload Component: Too many files alert does not show (multiple configs)

### ISSUE THREAD

**Issue by jackiejakob** [pearson-ux/web-components#169]
Alert for too many files selected does not show in the following configruations:

Windows10 / Edge 16 & 17
macOS 10.12 / Safari 11
iOS Safari
Win/FF
Mac/FF

Additional information:
The alert for file too large **does** show in the above configurations. 
The alert also **does** show in IE11.

Bug for issue #64

**Comment by davodey** [comment]
@jackiejakob can you double check this?  I got the error in firefox.  One thing to note, the messaging may not be clear.  Its upload up to 5 files at ONE TIME, not 5 files total.


![screen shot 2018-11-16 at 9 34 06 am](https://user-images.githubusercontent.com/5407196/48634447-c8484580-e982-11e8-8cbc-ad2414df2526.png)

**Comment by jackiejakob** [comment]
@davodey  I see it appearing now in FF and Mac/Safari. Maybe EJ fixed something in his latest commit.

Problem persists in: 
Windows10 / Edge 16 & 17

Could not test:
iOS Safari
