### ISSUE TITLE
[Bug] File Upload Component: Modal does not minimize in Win/Firefox 

### ISSUE THREAD

**Issue by jackiejakob** [pearson-ux/web-components#174]
Win10/FF (via Browserstack)
Steps: 
Upload a file.
Click minimize icon.
See minimize panel appear in footer but modal doesn't close.
![screen shot 2018-11-14 at 11 48 16 am](https://user-images.githubusercontent.com/30183956/48508417-61505280-e803-11e8-9a13-6fc44e398e37.png)

**Comment by davodey** [comment]
@jackiejakob did we fix this?

**Comment by jackiejakob** [comment]
@davodey No, this issue still happens--tested again in Win10/FF63. (Also realizing that the font in the minimized bar is different.)
![screen shot 2018-11-16 at 8 53 52 am](https://user-images.githubusercontent.com/30183956/48635543-502b5100-e97d-11e8-9d83-54e60accccd6.png)
