### ISSUE TITLE
Alert styles should be encapsulated

### ISSUE THREAD

**Issue by dengeist** [pearson-ux/web-components#179]
Light DOM children should be styled according to Elements, regardless of whether the parent document contains Elements

**Comment by antelopeb** [comment]
@dengeist -- can you supply some details on this one? It seems self-explanatory, but it's just vague enough to be dangerous 😄

**Comment by davodey** [comment]
@antelopeb the main container of this alert box has encapsulated styles, however the text is all in light dom, controlled by elements sdk.  I want to make the entire alert encapsulated so whether you have elements or not, it will render correctly.

**Comment by dengeist** [comment]
Correct me if I am wrong, but we could do this with `::slotted(selector)`, right? As long as _all_ children of the modal are at the top level, that should be fine
