### ISSUE TITLE
Table CSS

### ISSUE THREAD

**Issue by pauljadam** [pearson-ux/web-components#183]
Table - Pearson UX Framework
https://uxframework.pearson.com/c/tables

HTML Data Tables Demo/Tutorial:
http://pauljadam.com/demos/data-tables.html

Tables Concepts • Tables • WAI Web Accessibility Tutorials
https://www.w3.org/WAI/tutorials/tables/

WAI-ARIA Authoring Practices 1.1 #table 
http://w3c.github.io/aria-practices/#table
Need to use aria-sort on sortable column headers
If the table contains sortable columns or rows, aria-sort is set to an appropriate value on the header cell element for the sorted column or row as described in the section on grid and table properties.
http://w3c.github.io/aria-practices/examples/grid/dataGrids.html

DataTables example - Default ordering (sorting)
https://datatables.net/examples/basic_init/table_sorting.html

Sortable column headers need keyboard focus outlines, operability, and screen reader operability along with proper HTML/ARIA semantics for the data table and the sorted states.

**Comment by davodey** [comment]
We will not be adding a data table component, instead we will provide new table CSS based on Gravity / UXF.
