### ISSUE TITLE
Modal styles not rendering correctly in IE11

### ISSUE THREAD

**Issue by davodey** [pearson-ux/web-components#186]
Modal focus is off in IE11 and is rendering the older version of elements.  

The older version of elements should only be used in the last example, all the prior should use BETA.

![screen shot 2018-11-30 at 8 29 35 am](https://user-images.githubusercontent.com/5407196/49298314-45db7d80-f47a-11e8-818b-f783ee9633f8.png)

**Comment by dengeist** [comment]
Some discoveries: 

For the purposes of **styling only**, IE and Edge are not treating each modal as unique instances. Whichever style is invoked _last_ in DOM is the way all modals will be styled, regardless of their individual attributes. For instance, if the first modal does not use elements v1 but the second one does, _all_ will use elements v1. The reverse is true if an elements v1 modal is first and a new-elements modal is second.
