### ISSUE TITLE
Double focus when web component has tabindex=0

### ISSUE THREAD

**Issue by jackiejakob** [pearson-ux/web-components#193]
Elements sdk adds a focus outline to anything with a tabindex=0 so the toggle gets a second focus outline when added onto page with elements css on it (e.g., Pattern Lab).

![image](https://user-images.githubusercontent.com/30183956/49895630-c77dc480-fe05-11e8-8df6-9f65e9272450.png)

@dengeist @davodey @antelopeb

**Comment by davodey** [comment]
For now, lets fix this within the component.  

We can address elements when we switch over to gravity-styles

**Comment by jackiejakob** [comment]
So you want to assume that the toggle will be used with elements-css and remove the rounded focus style from within the toggle?

**Comment by davodey** [comment]
I guess what I'm saying is let's leave elements alone and fix the issue in the component, leaving the rounded style and cancel out the double box.

**Comment by jackiejakob** [comment]
Sorry, I didn't clarify: the box is from elements (generic focus outline for tabindex=0), the rounded is from within the component. 
But sounds good. I just wanted to bring up the concern that if a project isn't using elements css then it wouldn't get our focus outline style.

**Comment by davodey** [comment]
fixed
