### ISSUE TITLE
Dropdown Component

### ISSUE THREAD

**Issue by davodey** [pearson-ux/web-components#21]
Convert the existing dropdown markup into a fully functioning web component using the spec kit:

Spec Kit:
https://github.com/pearson-ux/web-component-spec-kit

This is currently blocked by: #20

**Comment by annehong** [comment]
Hi and sorry, 

There is a minor request from Mike Krolak that we follow the dropdown styles from Gravity, specifically this link: https://ux.pearson.com/gravity/c/inputs#select-dropdown

The reason why they want the change done here is that they want to use the same class names and re-use the same components across all learning app applications. They're trying to iron out all the inconsistencies. :)

Thank you,
Anne

**Comment by davodey** [comment]
@annehong this is in our gravity css and sdk:

https://ux.pearson.com/prototypes/gravity/?p=gravity-select

**Comment by annehong** [comment]
Awesome, thanks
