### ISSUE TITLE
Modal show/hide programmatic and shown on render

### ISSUE THREAD

**Issue by antelopeb** [pearson-ux/web-components#343]
The modal needs both a programmatic way to show/hide, as well as a way to show the modal on load. Something like these?

`<pearson-modal shown="true">`

and

`document.querySelector("pearson-modal").show()`

**Comment by davodey** [comment]
@antelopeb we do this, but theres a minor bug preventing it to open.  The attribute is 
open="true"

Ill fix it and submit for review.
