### ISSUE TITLE
[Modal]Need to remove scroll in modal

### ISSUE THREAD

**Issue by imalka-pearson** [pearson-ux/web-components#350]
- There is a **fix horizontal and vertical scroll bar** available when we integrate pearson-modal component. Could anyone provide a fix to remove fix scroll bar from the pearson-modal component end.

![Modal_Error](https://user-images.githubusercontent.com/45793725/71151493-d5a4c300-2259-11ea-80f8-27b9558f0643.png)

**Comment by davodey** [comment]
@imalka-pearson Can you tell me what browsers you see the scrollbar in?

**Comment by imalka-pearson** [comment]
I have tested in Mozilla and Chrome latest.

**Comment by davodey** [comment]
@imalka-pearson Windows, mac, both?

**Comment by davodey** [comment]
@imalka-pearson ok I see the issue.  I am going to change the property of overflow from 'scroll' to 'auto'.  This will eliminate unnecessary scrollbars, but still show when needed.  Does this work for you?

**Comment by davodey** [comment]
@imalka-pearson The following have been released and updated with with the solution I suggested.
- modal 1.1.1 
- wc full build 4.1.2 

Let me know if i can close the issue.

**Comment by imalka-pearson** [comment]
![alert_modal_fixed](https://user-images.githubusercontent.com/45793725/72223786-bc610f00-3598-11ea-84ff-eda3aebef7c8.png)

Issue has been fixed
