### ISSUE TITLE
UK - Pagination ellipsis issue

### ISSUE THREAD

**Issue by walkyv** [pearson-ux/web-components#359]
When the pagination component's “ellipsisat” attribute is not set and the user moves to the end of the pagination either by using the navigation buttons or by clicking the final page link, then the “Ellipsis” starts to appear.

![Pagination1](https://user-images.githubusercontent.com/47328314/72991915-c087fa80-3dea-11ea-8a9c-286a80be2c84.png)

![Pagination2](https://user-images.githubusercontent.com/47328314/72992633-00031680-3dec-11ea-9cad-f3a4a1f193ab.png)

Also when “ellipsisat” attribute is not set and the user visits the last page of the total pages and then moves to the first page using the [<] navigation button. Multiple ellipsis start appearing. When the user clicks on one of those ellipsis or click the [<] navigation button, then exceptions are thrown.

![Pagination3](https://user-images.githubusercontent.com/47328314/72992967-815aa900-3dec-11ea-89ea-0191138bf8f5.png)

![PaginationError](https://user-images.githubusercontent.com/47328314/72993000-8ddf0180-3dec-11ea-96ae-523dca5e4c29.png)

**Comment by davodey** [comment]
@walkyv issue is fixed, have the devs refresh cache if loading from CDN, or update their dependancies if they are hosting locally :)
