### ISSUE TITLE
UK - Icons are not being loaded in Safari browser 

### ISSUE THREAD

**Issue by walkyv** [pearson-ux/web-components#362]
Icons are not being loaded in Safari browser . 

**Root Cause**
Unable to download the SVG file via CDN as S3 bucket do not have permission to download the same 

SVG file - https://pearsonux.sfo2.cdn.digitaloceanspaces.com/css/p-icons-sprite-1.1.svg.gz

**Error Message** 
<Error>
    <Code>NoSuchKey</Code>
    <BucketName>pearsonux</BucketName>
    <RequestId>tx0000000000000d8f18d62-005e285935-37cb64-sfo2a</RequestId>
    <HostId>37cb64-sfo2a-sfo</HostId>
</Error>

**Comment by davodey** [comment]
@walkyv if you remove the .gz, the script will work.  There was an oversight in the docs on my end,  I'll update them asap.

new SVG file:
SVG file - https://pearsonux.sfo2.cdn.digitaloceanspaces.com/css/p-icons-sprite-1.1.svg
