### ISSUE TITLE
UK - Tab component titles collapsing when value is updated

### ISSUE THREAD

**Issue by walkyv** [pearson-ux/web-components#373]
We are identified an issue with Pearson-Tabs component. While we are trying to update the Tab’s title the whole Tab component UI get collapsed. 

As per the business requirement, I need to implement the following functionality:
- Show the counts only with the non-selected tabs.
- If the new record added, updated the tabs count accordingly.   

So, for these requirements, the tab title values are updated when a users clicks on a new tab but the titles in Tab component UI are collapsing and blending together.

![Screenshot1](https://user-images.githubusercontent.com/47328314/74232388-95454c80-4cc0-11ea-9546-467480ca9613.PNG)

![Screenshot2](https://user-images.githubusercontent.com/47328314/74232402-9b3b2d80-4cc0-11ea-8c61-e9a3656391f0.PNG)

![Screenshot3](https://user-images.githubusercontent.com/47328314/74232415-a42bff00-4cc0-11ea-96d3-7dc9e6ddff74.PNG)

**Comment by davodey** [comment]
@walkyv ahhh yah.  ok.  let me see what i can do.
