### ISSUE TITLE
UK - Header logout issue

### ISSUE THREAD

**Issue by walkyv** [pearson-ux/web-components#376]
### Logolink is not set 

When the logolink attribute on the Header component is not set, like so:
![image](https://user-images.githubusercontent.com/47328314/74526336-139d2b00-4f1b-11ea-9eba-4a8b96de8290.png)

And then I click to logout, nothing happens, the log out menu doesn't appear.
![image](https://user-images.githubusercontent.com/47328314/74526485-624ac500-4f1b-11ea-87ca-24093cce4af8.png)

The following errors are raised
![image](https://user-images.githubusercontent.com/47328314/74526645-b5247c80-4f1b-11ea-962e-fc0f47626129.png)

### Logolink is set

When the logolink attribute is set:
![image](https://user-images.githubusercontent.com/47328314/74527276-23b60a00-4f1d-11ea-8a6e-10c0a865629d.png)

And I click to logout, the menu appears and I can click on the logout menu item, but the 'logout' callback function is not executed.
![image](https://user-images.githubusercontent.com/47328314/74527622-18171300-4f1e-11ea-9f61-995306e7b3cc.png)

Callback
![image](https://user-images.githubusercontent.com/47328314/74526987-89ee5d00-4f1c-11ea-8769-f22834cbf492.png)

**Comment by davodey** [comment]
@walkyv are you still having this issue after the latest release?

**Comment by walkyv** [comment]
@davoday thanks for making the fix, the release has resolved the issue we were having.
