### ISSUE TITLE
UK - Modal can only be displayed by a button click or onload

### ISSUE THREAD

**Issue by walkyv** [pearson-ux/web-components#380]
We have a requirement for the modal to be displayed when a property changes to a certain value, e.g. note displayed on a button click or onload. 

Currently setting 'open = true' throws an error saying that the 'trigger' is null when its trying to disable the trigger.

**Code**
![image](https://user-images.githubusercontent.com/47328314/75047573-e0c8d900-54be-11ea-9a75-1f72978dbb06.png)
 
**Error**
![image](https://user-images.githubusercontent.com/47328314/75047655-0c4bc380-54bf-11ea-8eb7-a2cbc9d47b69.png)

**Code where error is raised**
![image](https://user-images.githubusercontent.com/47328314/75047705-24bbde00-54bf-11ea-85b3-65304c984960.png)

**Comment by davodey** [comment]
@walkyv you need to add the attribute 'showonload' to any modal not using a button.  This will catch the error and let you move on.

**Comment by davodey** [comment]
https://ux.pearson.com/web-components/docs/web-components/modal#optional

@walkyv let me know if this solves your issue.

**Comment by walkyv** [comment]
Hi David, there is a requirement to programmatically display the modal dependant on a variable change which I don't seem to be able to do. E.g. bind the variable to the 'open' attribute to display it.

**Comment by walkyv** [comment]
Hi David, we have a work around for this so the issue could be closed, we are only rendering the modal when attribute  === true and then adding the showonload attribute.
