### ISSUE TITLE
UK - Modal prevent modal from disappearing when clicking outside or pressing escape

### ISSUE THREAD

**Issue by walkyv** [pearson-ux/web-components#381]
We have a requirement to enforce a user selects an option on the modal, would it be possible to prevent the modal closing when a user clicks outside the model or presses escape?

e.g. Something like this?

$('#myModal').modal({
    backdrop: 'static',
    keyboard: false
})

**Comment by davodey** [comment]
@walkyv due to accessibility we cannot remove the escape functionality.  We may be able to disable the overlay click.  Let me think about this some more and get some additional guidance.
