### ISSUE TITLE
Tab panels forcing incorrect body copy color

### ISSUE THREAD

**Issue by whatevers** [pearson-ux/web-components#389]
This line results in all body content of the tab panels defaulting to #6A7070. Default body copy in Gravity should be #252525 (Charcoal)

https://github.com/pearson-ux/web-components/blob/1061c2e8f77ea4f09c5a75323cc99b4b3753cb14/tab-navigation/scss/style.scss#L16

**Comment by davodey** [comment]
Issue fixed.

tabs 1.4.2 released
wc 5.7.1 released.
