### ISSUE TITLE
Coachmark Accessibility issue while focus on Cross/close button

### ISSUE THREAD

**Issue by ashish-knowdl** [pearson-ux/web-components#417]
The person coachmark web component is working better to set focus to the X button once you open the coachmark in VoiceOver on iOS https://ux.pearson.com/web-components/docs/web-components/coach

But I do see a bug in the coachmark component on iOS where it only sets focus to the X button the first time you open the coachmark but if you open it again focus does not move to the x button. 

Both coachmarks have the same bug where it takes an extra double tap to activate the coachmark link and then it sets focus to the X button. So you have to activate the coachmark link twice to get it work correctly. 

Please refer below JIRA ticket for more details 
https://agile-jira.pearson.com/browse/ACDS-155160

**Comment by davodey** [comment]
@ashish-knowdl this has been fixed and released.

**Comment by ashish-knowdl** [comment]
@davodey  - We have verified this scenario with new version, but unfortunately we are facing same issue.
Please find recorded video of testing in below attached zip.  
[CoachmarkIssues.zip](https://github.com/pearson-ux/web-components/files/5261346/CoachmarkIssues.zip)

**Comment by davodey** [comment]
This appears to be a bug in VO safari and not with the component.  --- closing issue.
