### ISSUE TITLE
Create a JS styleguide 

### ISSUE THREAD

**Issue by davodey** [pearson-ux/web-components#49]
@dengeist suggested we put together a JS style guide to set some guidelines around how we all write our JS in our web components.   

@dengeist if you would like to take the lead on this and start creating a basic outline that would be great.  We can then re-group and discuss.

I think our Wiki may be a good place to hold this.

**Comment by annehong** [comment]
I don't know if this helps, but here's a sample of a JavaScript styleguide from Udacity:
<img width="622" alt="screen shot 2018-11-15 at 12 02 12 pm" src="https://user-images.githubusercontent.com/9653426/48578451-81991380-e8ce-11e8-92a7-f84ddcb2ca84.png">

http://udacity.github.io/frontend-nanodegree-styleguide/javascript.html

Let me know @dengeist  if the url doesn't work, then I will send you a pdf file of it.

There's also CSS and HTML style guides as well.

@antelopeb they have the semicolons, but JSX tutorials don't seem to use semicolons.

**Comment by davodey** [comment]
@annehong Nice! Thanks for sharing.
