### ISSUE TITLE
RFC: Custom label component

### ISSUE THREAD

**Issue by dengeist** [pearson-ux/web-components#91]
Attn @antelopeb, @davodey!

## Rationale
Components like the [toggle button](https://github.com/pearson-ux/web-components/pull/92) need external text labels so that consumers can accessibly describe them. Consumers should have granular control over the positions of and controls associated with their labels.

## Problem
Native labels in the Light DOM will not associate themselves with Shadow form controls because they are not in the same DOMs.

## Options
- Generate labels in every custom control. 
- Create a custom label component.

Option one is the approach currently taken in the toggle component. Every custom control would ship identical code for its own labels. This would bloat the delivery size of the components, albeit marginally. The label's position would be difficult to customize.

Under option two,  the custom label would expose a declarative API for associating itself with custom form controls, as well as use scripting to interact with its associated control on click, etc.. This custom control could then be targeted from the stylesheet in the Light Dom and positioned however the consumer wishes.

**Comment by davodey** [comment]
@dengeist I like option two.  I say we start by building the label component inside the toggle, so maybe in a folder called components?  Then, if we find ourselves building other form-based components, we can pull it out and make it a standalone.

**Comment by dengeist** [comment]
@davodey Bundling `pearson-label` with the toggle makes sense, but even if it's part of the `pearson-toggle` package, consumers would still have to import the label and toggle separately, so that the label can be independently positioned, and so positioning will be _easy_ for that matter. Given that constraint, I think the label should just be its own component.

**Comment by antelopeb** [comment]
I like option #2 as well. Like this, right? `<pearson-toggle label-id="id"></pearson-toggle>`

OR `<pearson-toggle>Label here</pearson-toggle>`.

**Comment by dengeist** [comment]
Closing until such a time as we need to plan a custom label
