### ISSUE TITLE
Toggle - pulling in old styling.

### ISSUE THREAD

**Issue by davodey** [pearson-ux/web-components#94]
I noticed that the focus state on toggle is using the outdated red focus outlines, not the thicker blue ones.  Lets check to make sure we're using the most current version of elements.

![screen shot 2018-09-07 at 8 45 54 am](https://user-images.githubusercontent.com/5407196/45229439-a3e13600-b27a-11e8-935b-3f037b9a0ea7.png)

**Comment by dengeist** [comment]
This one is my bad, @davodey. I built this back when the pink outline was the standard. If you point me to the design of the correct focus ring, I can fix it.
